### ISSUE TITLE
Permissions settings

### ISSUE THREAD

**Issue by lajoimat** [null93/chrome-milk#14]
Nice and useful extension!

However, it stops working when I change the "Read and Change Site Data" permission to  "When You click the Extension".

Would it be possible to give these access to the app only when the user request it?

Thanks

**Comment by null93** [comment]
I am glad you like the extension! I definitely agree that this should be implemented. I was able to replicate the behavior and I will try to work on it when I have a chance, but it might not be for a while. Thanks for your input and thanks for taking the time to submit this issue!

**Comment by null93** [comment]
Looking into this issue, unfortunately I was not able to make this happen. I looked at other implementations and the same issue exists in all cookie managers that I tested. If you have any insight as to how to make this happen, I am all ears! Just reopen the issue.

**Comment by lajoimat** [comment]
Thanks!
