### ISSUE TITLE
Dock window

### ISSUE THREAD

**Issue by HikariWS** [null93/chrome-milk#15]
I like how your extension is clean and provides all needed info for all current site's cookies!

Is it possible to get its info on a docked window, instead of a panel? I'd like to have it visible all time instead of having to click on it and having it closed when mouse leaves. It'd also me great if it automatically changes its info to show current tab.

This way I can position the window and just look at it to see current page/tab's cookies info.

**Comment by null93** [comment]
Thanks for taking the time to open an issue, I think its a great idea and I will see if I can implement it!

**Comment by HikariWS** [comment]
Tnx for the attention.

If you want an example TabFern does exactly that. I keep it on a window where I see all my browser windows and their tabs. When I need I just click on any tab and it brings that window to front and selects that tab.

**Comment by null93** [comment]
I am currently working on an updated version of the extension with this already implemented. When I find time to finalize it, I will release it with this feature! Thanks again for the idea.

**Comment by null93** [comment]
Just released v2.0.0 and this feature is implemented in that release. Just waiting for chrome to approve the update, stay tuned!
