### ISSUE TITLE
Internal pages load pretty wonky

### ISSUE THREAD

**Issue by narcolepticinsomniac** [null93/chrome-milk#16]
Chromium 86.0.4240.198

Popup always flashes "NO COOKIES FOUND" for a split second before loading the list of cookies. CSS is late, which in the popup, causes transitions to erroneously apply as it loads. On the 'options' page, there's a very noticeable FOUC, particularly obvious in the dark theme.

Mimicking Chromium's dark theme for the browser's internal pages is kinda cool, but leaving scrollbars bright white in a dark theme is one thing Chromium does which shouldn't be copied. Also, in options, you've got a couple useless scrollbars. You should use `overflow-y: auto;` instead of `overflow-y: scroll;`.

**Comment by null93** [comment]
Thanks for testing it out further and letting me know all the issues! Let me address everything:

> Popup always flashes "NO COOKIES FOUND" for a split second before loading the list of cookies

This is because it is loading the cookies, I can fix this by making a loading state. Unfortunately, chrome.cookies.getAll takes some time to execute and return all the cookies. Until then we assume that there are no cookies. A simple loading state would solve this IMO.

> CSS is late, which in the popup, causes transitions to erroneously apply as it loads. On the 'options' page, there's a very noticeable FOUC, particularly obvious in the dark theme.

This is because it initially loads with the light theme and once user preferences are loaded from chrome, it then updates it with the dark theme. This might not be something that can be fixed. If localStorage is faster than chrome.storage.local, then I might be able to cache some user options and load those initially. This may or may not be fixable unfortunately. 

> Mimicking Chromium's dark theme for the browser's internal pages is kinda cool, but leaving scrollbars bright white in a dark theme is one thing Chromium does which shouldn't be copied. Also, in options, you've got a couple useless scrollbars. You should use overflow-y: auto; instead of overflow-y: scroll;.

I am gonna guess that you are using Window? I use Mac myself and don't see those scroll bars. A simple `::-webkit-scrollbar {  display: none }` might solve all the issues. Might need your help to confirm the issue is gone with that one :)

**Comment by null93** [comment]
Hey @narcolepticinsomniac, thanks again for testing out the new version of the plugin. I fixed everything that I mentioned above and it is available in [2.0.1](https://github.com/null93/chrome-milk/releases/tag/2.0.1). Let me know if the scrollbars disappeared for you. Thanks!

**Comment by narcolepticinsomniac** [comment]
Loading much smoother. 

>  I use Mac myself and don't see those scroll bars.

![2020-12-10 00_25_43-](https://user-images.githubusercontent.com/14100003/101725426-a4cb2880-3a7e-11eb-97b4-12fc73b4561d.png)


> `::-webkit-scrollbar { display: none }`

Nah, you can't do that. That'll hide all the scrollbars. I guess, ideally, you'd figure out where in the script that overflow's determined, and change it to auto. If you're lazy like me, you can just override it: `nav, main > div{overflow-y:auto!important;}`. 

> leaving scrollbars bright white in a dark theme is one thing Chromium does which shouldn't be copied

You can try [this](https://pastebin.com/59Vs0HX3) in your global CSS - should solve both issues. If you like the scrollbars, you'd need to inject the CSS only in the dark theme. If you don't, you should make your own dark scrollbars for the dark theme.

**Comment by null93** [comment]
I think I am okay with removing them all together for now; no one needs those ugly things lol. Thanks for the screen shot, definitely looks awful with them there!

**Comment by narcolepticinsomniac** [comment]
> I think I am okay with removing them all together for now; no one needs those ugly things

I'm not sure you follow what I'm saying. The unnecessary ugly things are only the ones with the arrows in the screenshot. Removing scrollbars altogether also includes the very necessary ugly things for the main overflow. Those don't need to be ugly either - you can style em, like I did in the above CSS file.

**Comment by null93** [comment]
@narcolepticinsomniac Definitely followed what you were saying lol. You caught me at a moment of laziness. I suppose I can style them, if you are willing to test it out in Windows for me :)

Style Scrollbars: https://github.com/null93/chrome-milk/issues/20

**Comment by narcolepticinsomniac** [comment]
Code LGTM. Hook up a zip.

**Comment by null93** [comment]
Great, thank you! I linked it in #20.

**Comment by narcolepticinsomniac** [comment]
Yep. No more unnecessary scrollbars, and the necessary ones are there and functional. I like my scrollbars more utilitarian, with buttons and all, but that's not really essential for this UI. Figured you'd probably go minimal, which is fine. I'd at least give the scrollbar itself a slight variation of background color, and maybe `:hover` / `:active` states for the thumb as well.

Not a huge fan of the thumb being hidden till hover either, but these are all minor details, and your prerogative. They're there, they work, and they're not ugly - so LGTM.

**Comment by null93** [comment]
Yeah I'd like them to be very minimal. Thanks for testing it out on Windows for me, saved me a bunch of time!
