### ISSUE TITLE
Today is 100% load CPU via Milk

### ISSUE THREAD

**Issue by miraserver** [null93/chrome-milk#23]
Dont know why but some timed ago, 1 hour, milk is loaded CPU to 98%, only delete from chrome is stabilized situation. Please check the chrome plugin store, maybe someone hack ur account...

**Comment by null93** [comment]
Thank you for reporting this. I will try to look into it as soon as I can. Is there anything in particular that you did before that may have triggered it? I want to be able to recreate this issue. Did you import a lot of cookies or keep the fullscreen on for a long period of time? Any information would really help me try to recreate this issue and solve it.

**Comment by miraserver** [comment]
mmm to hard for diagnostic. No importing any cookie. Yeap, about 20+ tab open and pinned. Some other plugins installed.
I think maybe its 2.0.2 update bug? Because chrome store have 2.0.1 version but here is 2.0.2 ver released. But today i see in store chrome 2.0.2 version. Maybe plugins auto updated?
Just know 2.0.1 working perfect. No any issue.
Iv just works today...just visited some sites...and...woops, CPU loading...freeze...too slow chrome...

**Comment by null93** [comment]
Wow, I think you are right. This is happening to me as well when chrome updated the extension to 2.0.2. Really sorry about this bug. It somehow slipped through the cracks without me noticing it. In the process of reverting back and releasing 2.0.3, I accidentally unpublished the extension (thinking it would unpublished the last update). It might be a while till it goes through the web store's approval process.

**Comment by miraserver** [comment]
Mmm i say more. In chromium (orbita) 2.0.2 version working without this problem...

**Comment by null93** [comment]
That is weird because the bug involved an infinite loop when a cookie is set. Anyways, I fixed the issue in [2.1.0](https://github.com/null93/chrome-milk/releases/tag/2.1.0). Sorry for any inconvenience this caused.
