### ISSUE TITLE
Bug - mobile import json not working

### ISSUE THREAD

**Issue by miraserver** [null93/chrome-milk#33]
So, about mobility. I dont know why official mobile chrome do not support addons but we have also good mobile browser based on chromium (blink) and Yandex browser support addons from chrome official store.

Now what we can - on android install Yandex Browser - https://play.google.com/store/apps/details?id=com.yandex.browser&hl=en&gl=US

Now u can go to Milk official chrome page and install it. Great. Milk is working. Opening, Possible clicks and etc.
But when i try to import json files - nothing happened. And milk is freeze i think:((

Iv also tested CookieBro and Cookie-Editor with mobile Yandex browser - and import works here perfect.

**Comment by null93** [comment]
@miraserver I will not be supporting Yandex browser or anything mobile. It is very much out of scope of what this extension is intended for.

**Comment by miraserver** [comment]
yeap i undestand.
 iv just ask because its chrome. Only core but...
did u think its different logic? chromium and chrome

anywhy, i think milk is support chromium core but maybe some small java code not work correct on ARM platform...or works slowly. 

this is my guess and my observation. Let others know that the plugin works in the mobile version chromium, but the import does not work and as u say you cannot guarantee that it will work.

**Comment by null93** [comment]
Not sure about Android but they are definitely different even if both share a code base. On the other hand,  the Chrome app on iPhone is just a Safari skin (I think).
