### ISSUE TITLE
[Feature request] Protect cookies

### ISSUE THREAD

**Issue by narcolepticinsomniac** [null93/chrome-milk#7]
I've been using editthiscookie for years for the sole purpose of protecting individual login or pref cookies from being deleted when cookies are cleared. It recently quit working, so I've been trying all the alternative cookie managers, and none seem to be capable of protecting individual cookies AFAICT. Yours has a lock icon, so I was optimistic, but it seems to be just an indicator for "secure".

**Comment by null93** [comment]
Thanks for the feedback, I like the idea. I will look into implementing this when I have some spare time :)

**Comment by null93** [comment]
Wow, sorry this took so long to implement but I did not find much time to work on this project. That being said, I just released v2.0.0 and this feature is implemented in that release alongside blocking cookies and much more. Just waiting for chrome to approve the update.

**Comment by narcolepticinsomniac** [comment]
Better late than never! Only tested briefly, but protecting cookies seems pretty flawless so far. 

I've been using a locally modified version of SyncMyCookie, which is nowhere near as convenient, since it only initializes cookies on browser/window launch, and I've never gotten around to improving it in that aspect.

One major bonus I've noticed since using SyncMyCookie though, has been the ability to dynamically update "protected/saved" cookies. Some sites may require refreshed values for user session cookies to keep working correctly, or some pref cookies may add additional pref values to the same cookie. 

More often than not, if the expiration/session is modified, you want those locked in, if protected, but there'll be many instances where it's useful to be able to allow the cookie's actual value to update dynamically.

**Comment by null93** [comment]
I am really glad you like it and thank you for testing it before it releases to the chrome store, it is much appreciated! As far as allowing values to change on a protected cookie, it is an interesting idea but might get confusing. It would need to be two separate things in my opinion. I will try to revisit this idea on my next sprint! Thanks again for using the extension and providing your feedback!

P.S. It would be great if you can leave a review on the chrome webstore :)
https://chrome.google.com/webstore/detail/milk-%E2%80%94-cookie-manager/haipckejfdppjfblgondaakgckohcihp

**Comment by narcolepticinsomniac** [comment]
> It would be great if you can leave a review on the chrome webstore

Done. Used the dev account for credibility, since all my throwaways have absurd names. =)
